name: PHP Composer

on:
  push:
    branches: [ "main", "hicham68-patch-2" ]
  pull_request:
    branches: [ "main", "hicham68-patch-2" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Remplacez par la version nécessaire
        extensions: mbstring, intl, ctype, iconv
        tools: composer

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check if lock file needs update
      run: composer update --lock
      continue-on-error: true

    - name: Commit lockfile changes if updated
      if: success() && steps.composer-cache.outputs.cache-hit == 'false'
      run: |
        git config --global user.name
